/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourisim;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import oracle.jdbc.*;
import oracle.jdbc.pool.*;
import oracle.sql.*;
import java.sql.*;
import java.math.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Msys
 */
public class AddGuide extends javax.swing.JFrame {

     EntityManagerFactory emf=Persistence.createEntityManagerFactory("TourisimPU");
     EntityManager em=emf.createEntityManager();
     EntityManager ememployee=Persistence.createEntityManagerFactory("TourisimPU").createEntityManager();
    /**
     * Creates new form AddGuide
     */
    private ButtonGroup radio1=new ButtonGroup();
    public AddGuide() {
        initComponents();
        super.pack();
        super.setLocationRelativeTo(null);
        super.setSize(730, 520);
        radio1.add(jRadioButtonmale);
        radio1.add(jRadioButtonfemale);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldHire = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        arabic = new javax.swing.JCheckBox();
        chinese = new javax.swing.JCheckBox();
        english = new javax.swing.JCheckBox();
        french = new javax.swing.JCheckBox();
        spanish = new javax.swing.JCheckBox();
        turkish = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(740, 391));
        setResizable(false);
        setSize(new java.awt.Dimension(710, 391));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 391));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 56)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 170, 183));
        jLabel9.setText("  Add Guide");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 170, 183));
        jLabel1.setText("Personal ID:");

        jTextFieldID.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 170, 183));
        jLabel5.setText("First Name:");

        jTextFieldFN.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldFN.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 170, 183));
        jLabel2.setText("Last Name:");

        jTextFieldLN.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldLN.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 170, 183));
        jLabel6.setText("E-mail Address:");

        jTextFieldEmail.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 170, 183));
        jLabel10.setText("Address:");

        jTextFieldAddress.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldAddress.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 170, 183));
        jLabel11.setText("Birth Date:");

        jTextFieldBDate.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldBDate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 170, 183));
        jLabel12.setText("Hire Date:");
        jLabel12.setToolTipText("");

        jTextFieldHire.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldHire.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 170, 183));
        jLabel13.setText("Gender:");

        jRadioButtonmale.setBackground(new java.awt.Color(32, 170, 183));
        jRadioButtonmale.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jRadioButtonmale.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonmale.setText("Male");
        jRadioButtonmale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRadioButtonfemale.setBackground(new java.awt.Color(32, 170, 183));
        jRadioButtonfemale.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jRadioButtonfemale.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonfemale.setText("Female");
        jRadioButtonfemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 170, 183));
        jLabel3.setText("Languges:");

        arabic.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        arabic.setForeground(new java.awt.Color(32, 170, 183));
        arabic.setText("Arabic");
        arabic.setContentAreaFilled(false);
        arabic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chinese.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        chinese.setForeground(new java.awt.Color(32, 170, 183));
        chinese.setText("Chinese");
        chinese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        english.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        english.setForeground(new java.awt.Color(32, 170, 183));
        english.setText("English");
        english.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        french.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        french.setForeground(new java.awt.Color(32, 170, 183));
        french.setText("French");
        french.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        spanish.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        spanish.setForeground(new java.awt.Color(32, 170, 183));
        spanish.setText("Spanish");
        spanish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        turkish.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        turkish.setForeground(new java.awt.Color(32, 170, 183));
        turkish.setText("Turkish");
        turkish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(32, 170, 183));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(32, 170, 183));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(83, 44));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(arabic, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chinese, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(french, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spanish, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(turkish, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(159, 159, 159))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButtonmale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(48, 48, 48)
                                    .addComponent(jRadioButtonfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addComponent(jTextFieldHire)
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldBDate)
                                .addComponent(jTextFieldAddress)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jTextFieldLN)
                                .addComponent(jTextFieldFN, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldHire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arabic)
                    .addComponent(chinese)
                    .addComponent(english)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turkish)
                    .addComponent(spanish)
                    .addComponent(french))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonfemale)
                    .addComponent(jRadioButtonmale)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        super.setVisible(false);
        Login_Admin.ae.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        try{
        if(!jTextFieldID.getText().isEmpty()&&!jTextFieldFN.getText().isEmpty()&&!jTextFieldLN.getText().isEmpty()
            &&!jTextFieldBDate.getText().isEmpty()&&!jTextFieldAddress.getText().isEmpty()&&!jTextFieldEmail.getText().isEmpty()
               &&!jTextFieldHire.getText().isEmpty()&&(jRadioButtonmale.isSelected()^jRadioButtonfemale.isSelected())
               &&(arabic.isSelected()||english.isSelected()||turkish.isSelected()||french.isSelected()
               ||spanish.isSelected()||chinese.isSelected()))
        {
            
            Person person=new Person();
        Gender gender=new Gender();
        EmployeeType et=new EmployeeType();
        Employeee employee=new Employeee();
        Adminstrator admin=new Adminstrator();
        Languages languages=new Languages();
        
        BigDecimal bigID=BigDecimal.valueOf(Long.parseLong(this.jTextFieldID.getText()));
        person.setPersonalId(bigID);
        employee.setPersonalId(person);
        person.setFirstName(this.jTextFieldFN.getText()); person.setLastName(this.jTextFieldLN.getText());
        person.setEmailAdress(this.jTextFieldEmail.getText()); person.setAddress(this.jTextFieldAddress.getText());
         String BDate=this.jTextFieldBDate.getText();  
         String HireDate=this.jTextFieldHire.getText(); 
        try {  
            Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(BDate);
            person.setBdate(date1);
             Date date2=new SimpleDateFormat("dd/MM/yyyy").parse(HireDate);
             employee.setHireDate(date2);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Wrong Date Format!(dd/MM/YYYY)", "Information", JOptionPane.WARNING_MESSAGE);
        }//end of catch
        if(jRadioButtonmale.isSelected())
        {
            gender.setGenderType("M");
            person.setGenderType(gender);
        }
            
        else if(jRadioButtonfemale.isSelected())
        {
             gender.setGenderType("F");
            person.setGenderType(gender);
        }
        et.setEmployeeType("G");
        employee.setEmployeeType(et);
        BigDecimal bigAID=BigDecimal.valueOf(Long.parseLong(Admin_Register.AID));
        admin.setAid(bigAID);
        employee.setAid(admin);
        
        //for eid:
        Query qry=ememployee.createNamedQuery("Employeee.findAllorder");
        Object guide_lang=ememployee.createEntityGraph("GUIDE_LANGUAGES");
        
        List<Employeee> employeelist=qry.getResultList();
        BigDecimal EID = null;
        for(Employeee e:employeelist)
        {
            EID=e.getEmploymentId();
        }
        
          int employeeID;
        if(EID==null)
        {
            employeeID=50;
        }
        else
        {
            employeeID=EID.intValue()+1;
        }
        BigDecimal bigemplyeeID=BigDecimal.valueOf(employeeID);
        employee.setEmploymentId(bigemplyeeID);
        //employee.setEmploymentId(employee.getEmploymentId());
      
       
      
         
        
        em.getTransaction().begin();
        em.persist(person);
        em.persist(employee);
        em.getTransaction().commit();
        em.close();
        ememployee.close();
        
               OracleDataSource ods;
        try {
            ods = new OracleDataSource(); ods.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ods.setUser("c##Travel"); ods.setPassword("987654");
              
              // DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
               String url,user,password;
               url="jdbc:oracle:thin:@localhost:1521:xe";
               user="c##Travel";
               password="987654";
                Connection con=ods.getConnection();
               //Connection con=DriverManager.getConnection(url,user,password);
               Statement stmt=con.createStatement();
               con.setAutoCommit(false);
               String sqlstr = null;

               if(arabic.isSelected())
               {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"Arabic"+"')";
                   stmt.executeUpdate(sqlstr);
               }
                        
               if(english.isSelected())
               {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"English"+"')";
                   stmt.executeUpdate(sqlstr);
               }
              if(spanish.isSelected())
             {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"Spanish"+"')";
                   stmt.executeUpdate(sqlstr);
               }
               if(turkish.isSelected())
                    {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"Turkish"+"')";
                   stmt.executeUpdate(sqlstr);
               }
               if(chinese.isSelected())
                   {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"Chinese"+"')";
                   stmt.executeUpdate(sqlstr);
               }
               if(french.isSelected())
                    {
                   sqlstr="insert into GUIDE_LANGUAGES values("+employeeID+",'"+"French"+"')";
                   stmt.executeUpdate(sqlstr);
               }
                        
               con.commit();
               con.close();
           } catch (SQLException ex) {
               Logger.getLogger(AddGuide.class.getName()).log(Level.SEVERE, null, ex);
           }
          
            jTextFieldID.setText(null); jTextFieldFN.setText(null); jTextFieldLN.setText(null);
        jTextFieldAddress.setText(null); jTextFieldEmail.setText(null); jTextFieldBDate.setText(null);
        jTextFieldHire.setText(null); 
        arabic.setSelected(false); english.setSelected(false); chinese.setSelected(false);
        french.setSelected(false); turkish.setSelected(false); spanish.setSelected(false);
        radio1.clearSelection();
         JOptionPane.showMessageDialog(this, "Staff Added Successfully "+"\nYour Employment ID is: "+employeeID, "Information", JOptionPane.INFORMATION_MESSAGE);

        }//end of else
        else
        JOptionPane.showMessageDialog(this, "Make sure to fill all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
    }
       catch(Exception e)
        {
            Logger.getLogger(AddGuide.class.getName()).log(Level.SEVERE, null, e); 
            jTextFieldID.setText(null); jTextFieldFN.setText(null); jTextFieldLN.setText(null);
        jTextFieldAddress.setText(null); jTextFieldEmail.setText(null); jTextFieldBDate.setText(null);
        jTextFieldHire.setText(null); 
        arabic.setSelected(false); english.setSelected(false); chinese.setSelected(false);
        french.setSelected(false); turkish.setSelected(false); spanish.setSelected(false);
        radio1.clearSelection();
            JOptionPane.showMessageDialog(this, "This Employee has Already Register Before!", "Warning", JOptionPane.WARNING_MESSAGE);
           
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGuide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arabic;
    private javax.swing.JCheckBox chinese;
    private javax.swing.JCheckBox english;
    private javax.swing.JCheckBox french;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFN;
    private javax.swing.JTextField jTextFieldHire;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLN;
    private javax.swing.JCheckBox spanish;
    private javax.swing.JCheckBox turkish;
    // End of variables declaration//GEN-END:variables
}
