/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourisim;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.SystemTray;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static tourisim.Available_Hotels.count;
import static tourisim.issueticket.chooseoffer;
import static tourisim.issueticket.falg;
import static tourisim.issueticket.offername;
import static tourisim.issueticket.sendMail;

/**
 *
 * @author Msys
 */
public class Available_Car extends javax.swing.JFrame {
EntityManagerFactory emf=Persistence.createEntityManagerFactory("TourisimPU");
     EntityManager em=emf.createEntityManager();
    EntityManager eoffer=Persistence.createEntityManagerFactory("TourisimPU").createEntityManager();
    static int count=1;
    Icon car=null;
    /**
     * Creates new form Available_Car
     */
    public Available_Car() {
        initComponents();
        super.pack();
        super.setLocationRelativeTo(null);
         Color c=new Color(32,170,183);
        //border for buttons and it's thickness
        jButton2.setBorder(BorderFactory.createLineBorder(c, 4));
        car=new ImageIcon(getClass().getResource("/Images/honda.jpeg"));
        jButton1.setIcon(car);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 170, 183));
        jLabel1.setText("Available Cars");

        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(32, 170, 183));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nexthotel.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(count==0)
        {
             car=new ImageIcon(getClass().getResource("/Images/honda.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
        else if(count==1)
        {
             car=new ImageIcon(getClass().getResource("/Images/audi.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
       else if(count==2)
        {
            car=new ImageIcon(getClass().getResource("/Images/toyota.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
        else if(count==3)
        {
            car=new ImageIcon(getClass().getResource("/Images/kia.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
       else if(count==4)
        {
            car=new ImageIcon(getClass().getResource("/Images/cadillac.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
       else if(count==5)
        {
            car=new ImageIcon(getClass().getResource("/Images/mercedes.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
       else if(count==6)
        {
            car=new ImageIcon(getClass().getResource("/Images/hyundai.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
       else if(count==7)
        {
            car=new ImageIcon(getClass().getResource("/Images/ford.jpeg"));
            jButton1.setIcon(car);
            count++;
        }
        else if(count==8)
        {
            car=new ImageIcon(getClass().getResource("/Images/peugeot.jpeg"));
            jButton1.setIcon(car);
            count=0;
        }
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{    
        RegisterClients register=new RegisterClients();
       
                   
        Query qry=eoffer.createNamedQuery("TakeCar.findAllorder");
       Query qryreg=eoffer.createNamedQuery("RegisterClients.findAllorder");
        
        java.util.List<TakeCar> carlist=qry.getResultList();
        TakeCar takecar=new TakeCar();
        Clients client=new Clients();
        Cars car=new Cars();
        BigDecimal rowcount = null;
        String HotelName="";
        BigInteger price=null;
        
        
        for(TakeCar tc:carlist)
        {
            rowcount=tc.getRawCount();
        }
        int rowid;
        if(rowcount==null)
        {
            rowid=1;
        }
        else
        {
            rowid=rowcount.intValue()+1;
        }
       
        BigDecimal bigrawID=BigDecimal.valueOf(rowid);
        takecar.setRawCount(bigrawID);
        BigDecimal bdpassport=BigDecimal.valueOf(Long.parseLong(question.passid));
       client.setPassportId(bdpassport);
        takecar.setPassportId(client);
        takecar.setCheckinDate(Take_Car.jDateChooser1.getDate());
        takecar.setCheckoutDate(Take_Car.jDateChooser2.getDate());
 
        //room.setNumberOfRooms(BigInteger.valueOf(numberofromm));
        String desc = ((ImageIcon)jButton1.getIcon()).getDescription();
        if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/audi.jpeg"))
        {
                    car.setCarTypr("Audi");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("170"))));
                    takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
                         
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/cadillac.jpeg"))
        {
            car.setCarTypr("Cadliac");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("310"))));
                    takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
                    
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/ford.jpeg"))
        {
           car.setCarTypr("Ford");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("265"))));
                    takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/honda.jpeg"))
        {            
            car.setCarTypr("Honda");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("250"))));
                   takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);            
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/hyundai.jpeg"))
        {
            car.setCarTypr("Hyundai");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("150"))));
                 takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price); 
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/kia.jpeg"))
        {
            car.setCarTypr("KIA");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("190"))));
                   takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/mercedes.jpeg"))
        {
            car.setCarTypr("Mercedes");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("350"))));
                 takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
            
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/peugeot.jpeg"))
        {
            car.setCarTypr("Peugeot");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("115"))));
                   takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
        }
        else if(desc.equals("file:/C:/Users/Msys/OneDrive/Desktop/Database/Tourisim/build/classes/Images/toyota.jpeg"))
        {
            car.setCarTypr("Toyota");
                    car.setPrice((BigInteger.valueOf(Long.parseLong("173"))));
                    takecar.setCarType(car);
                    price=car.getPrice();
                    price=BigInteger.valueOf(price.intValue());
                    takecar.setPrice(price);
            
        }
       
         
             java.util.List<RegisterClients> reglist=qryreg.getResultList();
            BigDecimal regID = null;
        for(RegisterClients rc:reglist)
        {
           regID=rc.getRegisteerId();
        }
        
          int registerID;
        if(regID==null)
        {
         registerID=20;   
        }
        else
        {
           registerID=regID.intValue()+1; 
        }
        BigDecimal bigregisterID=BigDecimal.valueOf(registerID);
        register.setRegisteerId(bigregisterID);
        register.setRegisteerId(register.getRegisteerId());
        client.setPassportId(bdpassport);
        register.setPassportId(client);
        ClientType ctype=new ClientType();
        ctype.setClientsType("nt");
        register.setClientsType(ctype);
        issueticket.totalpricereg=issueticket.totalpricereg+price.intValue();
        register.setTotalPrice(BigInteger.valueOf(issueticket.totalpricereg));
        issueticket.totalprice=register.getTotalPrice().toString();
        
        
        //register.setTotalPrice(price);
        if(issueticket.cheack)
        {
              JOptionPane.showMessageDialog(this, "Successfully Issueing The Ticket And Booking The Room And Taking Car", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else
              JOptionPane.showMessageDialog(this, "Successfully Issueing The Ticket And Taking Car", "Information", JOptionPane.INFORMATION_MESSAGE);
      
//        this.dispose();
//        question que=new question();
//        que.setVisible(true);
//        two_options.al.setVisible(false);
        
         em.persist(register);
         em.getTransaction().begin();
        em.persist(takecar);
        em.getTransaction().commit();
        em.close();
        
        //email:
        
        sendMail("air333761@gmail.com");
        
        
             if(falg)
             {
            try {
                Thread.sleep(7000);
            } catch (InterruptedException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
                  if (SystemTray.isSupported()) {
            issueticket td = new issueticket();
            try {
                td.displayTray();
            } catch (AWTException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.err.println("System tray not supported!");
        }
             }
             //Bill:
             issueticket.room="yes"; issueticket.car="yes"; issueticket.chooseoffer="no"; issueticket.offername="-----";
             new try_report().setVisible(true);
             
        
        }
        
        catch(Exception e)
        {
           Logger.getLogger(WithTrip.class.getName()).log(Level.SEVERE, null, e); 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Available_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Available_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Available_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Available_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Available_Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
