/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourisim;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import oracle.jdbc.pool.OracleDataSource;
import static tourisim.updateEmployee.arabicf;
import static tourisim.updateEmployee.chinesef;
import static tourisim.updateEmployee.englishf;
import static tourisim.updateEmployee.frenchf;
import static tourisim.updateEmployee.spanishf;
import static tourisim.updateEmployee.turkishf;

/**
 *
 * @author Msys
 */
public class DeleteEmployee extends javax.swing.JFrame {
private ButtonGroup radio1=new ButtonGroup();
EntityManagerFactory emf=Persistence.createEntityManagerFactory("TourisimPU");
 EntityManager em=emf.createEntityManager();
 EntityManager ememployee=Persistence.createEntityManagerFactory("TourisimPU").createEntityManager();
 static boolean  arabicf=false,englishf=false,spanishf=false,turkishf=false,frenchf=false,chinesef=false;
    /**
     * Creates new form DeleteEmployee
     */
    public DeleteEmployee() {
        initComponents();
        super.pack();
        super.setLocationRelativeTo(null);
        super.setSize(730, 520);
       radio1.add(jRadioButtonMale);
       radio1.add(jRadioButtonFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldHire = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldemptype = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        arabic = new javax.swing.JCheckBox();
        french = new javax.swing.JCheckBox();
        chinese = new javax.swing.JCheckBox();
        spanish = new javax.swing.JCheckBox();
        english = new javax.swing.JCheckBox();
        turkish = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(740, 391));
        setResizable(false);
        setSize(new java.awt.Dimension(710, 391));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 391));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 56)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 170, 183));
        jLabel9.setText("Delete Employee");

        jButtonBack.setBackground(new java.awt.Color(32, 170, 183));
        jButtonBack.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.setBorder(null);
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.setPreferredSize(new java.awt.Dimension(146, 44));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(32, 170, 183));
        jButtonDelete.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonDetails.setBackground(new java.awt.Color(32, 170, 183));
        jButtonDetails.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButtonDetails.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetails.setText("Get Details");
        jButtonDetails.setBorder(null);
        jButtonDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 170, 183));
        jLabel3.setText("Employment ID:");

        jTextFieldEID.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldEID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 170, 183));
        jLabel1.setText("Personal ID:");

        jTextFieldID.setEditable(false);
        jTextFieldID.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 170, 183));
        jLabel5.setText("First Name:");

        jTextFieldFN.setEditable(false);
        jTextFieldFN.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldFN.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 170, 183));
        jLabel2.setText("Last Name:");

        jTextFieldLN.setEditable(false);
        jTextFieldLN.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldLN.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 170, 183));
        jLabel6.setText("E-mail Address:");

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 170, 183));
        jLabel10.setText("Address:");

        jTextFieldAddress.setEditable(false);
        jTextFieldAddress.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldAddress.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 170, 183));
        jLabel11.setText("Birth Date:");

        jTextFieldBdate.setEditable(false);
        jTextFieldBdate.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldBdate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 170, 183));
        jLabel12.setText("Hire Date:");
        jLabel12.setToolTipText("");

        jTextFieldHire.setEditable(false);
        jTextFieldHire.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldHire.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(32, 170, 183));
        jLabel14.setText("Employee Type:");

        jTextFieldemptype.setEditable(false);
        jTextFieldemptype.setBackground(new java.awt.Color(32, 170, 183));
        jTextFieldemptype.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(32, 170, 183));
        jLabel15.setText("Guide Languges:");
        jLabel15.setToolTipText("");

        arabic.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        arabic.setForeground(new java.awt.Color(32, 170, 183));
        arabic.setText("Arabic");
        arabic.setContentAreaFilled(false);
        arabic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        french.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        french.setForeground(new java.awt.Color(32, 170, 183));
        french.setText("French");
        french.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        french.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchActionPerformed(evt);
            }
        });

        chinese.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        chinese.setForeground(new java.awt.Color(32, 170, 183));
        chinese.setText("Chinese");
        chinese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        spanish.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        spanish.setForeground(new java.awt.Color(32, 170, 183));
        spanish.setText("Spanish");
        spanish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        english.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        english.setForeground(new java.awt.Color(32, 170, 183));
        english.setText("English");
        english.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        turkish.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        turkish.setForeground(new java.awt.Color(32, 170, 183));
        turkish.setText("Turkish");
        turkish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turkish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkishActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 170, 183));
        jLabel13.setText("Gender:");

        jRadioButtonMale.setBackground(new java.awt.Color(32, 170, 183));
        jRadioButtonMale.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jRadioButtonMale.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRadioButtonFemale.setBackground(new java.awt.Color(32, 170, 183));
        jRadioButtonFemale.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jRadioButtonFemale.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arabic, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(french, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chinese, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spanish, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turkish, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(24, 24, 24)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldBdate)
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jTextFieldFN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldemptype)
                                    .addComponent(jTextFieldEID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldID)
                                        .addComponent(jTextFieldLN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldHire, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jRadioButtonFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextFieldHire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldemptype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arabic)
                            .addComponent(chinese)
                            .addComponent(english))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turkish)
                            .addComponent(spanish)
                            .addComponent(french))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        super.setVisible(false);

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void frenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frenchActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishActionPerformed

    private void turkishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turkishActionPerformed

    private void jButtonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsActionPerformed
        // TODO add your handling code here:
        try{
        arabic.setSelected(false); english.setSelected(false); french.setSelected(false);
        spanish.setSelected(false); chinese.setSelected(false); turkish.setSelected(false);
        arabicf=false; englishf=false; frenchf=false; spanishf=false;
        chinesef=false; turkishf=false;
        radio1.clearSelection();
               
         Query qry=ememployee.createNamedQuery("Employeee.findAllorder");
         Query qr=ememployee.createNamedQuery("Person.findAll");
         List <Person> personlist=qr.getResultList();
        List<Employeee> employeelist=qry.getResultList();
        BigDecimal EID = null;
       Person person = null;
       Gender gender=new Gender();
       boolean flag=false;
        for(Employeee e:employeelist)
        {
            if(e.getEmploymentId().compareTo(BigDecimal.valueOf(Long.parseLong(this.jTextFieldEID.getText())))==0)
            {
                flag=true;
                person=e.getPersonalId();
                BigDecimal b=person.getPersonalId();
                SimpleDateFormat dateForm=new SimpleDateFormat("dd/MMM/yyyy");
                jTextFieldID.setText(person.getPersonalId().toString());
                jTextFieldFN.setText(person.getFirstName()); jTextFieldLN.setText(person.getLastName());
                jTextFieldEmail.setText(person.getEmailAdress()); jTextFieldAddress.setText(person.getAddress());
                jTextFieldHire.setText(dateForm.format(e.getHireDate())); jTextFieldBdate.setText(dateForm.format(person.getBdate()));
                Gender g=person.getGenderType();    
                
                EmployeeType et=e.getEmployeeType();
                if(g.getGenderType().equals("M"))
                {
                jRadioButtonMale.setSelected(true);
                }
                if(g.getGenderType().equals("F"))
                {
                jRadioButtonFemale.setSelected(true);
                }
               if(et.getEmployeeType().equals("S"))
               {
                   jTextFieldemptype.setText("Staff");
               }     
               if(et.getEmployeeType().equals("G"))
               {
                   jTextFieldemptype.setText("Guide");
               } 
               OracleDataSource ods;
        try {
            ods = new OracleDataSource(); ods.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ods.setUser("c##Travel"); ods.setPassword("987654");
            Connection con=ods.getConnection();
            Statement stmt=con.createStatement();
            String strsql="select * from GUIDE_LANGUAGES";
            ResultSet rs1=stmt.executeQuery(strsql);
            String s="";
            while(rs1.next()){
                
            if(e.getEmploymentId().compareTo(rs1.getBigDecimal(1))==0)
            {
                if(rs1.getString(2).equals("Arabic"))
                {
                  arabic.setSelected(true);
                  arabicf=true;
                }
                    
                 if(rs1.getString(2).equals("English"))
                 {
                     english.setSelected(true);
                     englishf=true;
                 }
              if(rs1.getString(2).equals("Spanish"))
              {
                  spanish.setSelected(true);
                  spanishf=true;
              }
             
               if(rs1.getString(2).equals("Turkish"))
               {
                  turkish.setSelected(true);
                  turkishf=true;
               }
                   
               if(rs1.getString(2).equals("Chinese"))
               {
                 chinese.setSelected(true);
                 chinesef=true;
               }
                   
               if(rs1.getString(2).equals("French"))
               {
                   french.setSelected(true);
                   frenchf=true;
               }
                  
            }
            }
            con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(Admin_Register.class.getName()).log(Level.SEVERE, null, ex);
        }
               
     
            }//end if 
        }//end for loop
        if(!flag)
        {
            jTextFieldFN.setText(null); jTextFieldLN.setText(null);
            jTextFieldEmail.setText(null);jTextFieldID.setText(null);
            jTextFieldAddress.setText(null);
         jTextFieldHire.setText(null); jTextFieldBdate.setText(null);
         jTextFieldemptype.setText(null); //jTextFieldguidelang.setText(null);
         radio1.clearSelection();
         
         
            JOptionPane.showMessageDialog(this, "Employee Not Found!", "Information", JOptionPane.WARNING_MESSAGE); 
        }
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Make sure to fill all fields!", "Information", JOptionPane.WARNING_MESSAGE);
        }
      
    }//GEN-LAST:event_jButtonDetailsActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        OracleDataSource ods;
        
        try {
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ods.setUser("c##Travel"); ods.setPassword("987654");
            Connection con=ods.getConnection();
              int personalid=Integer.parseInt(jTextFieldID.getText());
              int employmentid=Integer.parseInt(jTextFieldEID.getText());        
            String qrylang="Delete GUIDE_LANGUAGES where EID="+employmentid;
            PreparedStatement pslang=con.prepareStatement(qrylang);
            pslang.executeUpdate();
             String qryemp="Delete EMPLOYEEE where EMPLOYMENT_ID="+employmentid;
            PreparedStatement psemp=con.prepareStatement(qryemp);
            psemp.executeUpdate();
            String qry="Delete Person where PERSONAL_ID="+personalid;
            PreparedStatement ps=con.prepareStatement(qry);
            ps.executeUpdate();
               
               jTextFieldFN.setText(null); jTextFieldLN.setText(null); jTextFieldEID.setText(null);
            jTextFieldEmail.setText(null);jTextFieldID.setText(null);
            jTextFieldAddress.setText(null);
         jTextFieldHire.setText(null); jTextFieldBdate.setText(null);
         jTextFieldemptype.setText(null); 
         radio1.clearSelection();
         arabic.setSelected(false); english.setSelected(false); french.setSelected(false);
        spanish.setSelected(false); chinese.setSelected(false); turkish.setSelected(false);
        
            JOptionPane.showMessageDialog(this, "Deleted Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE); 
               
           } catch (SQLException ex) {
               Logger.getLogger(AddGuide.class.getName()).log(Level.SEVERE, null, ex);
           }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "You have to get details before Delete!", "Information", JOptionPane.WARNING_MESSAGE);
        }

     
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arabic;
    private javax.swing.JCheckBox chinese;
    private javax.swing.JCheckBox english;
    private javax.swing.JCheckBox french;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBdate;
    private javax.swing.JTextField jTextFieldEID;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFN;
    private javax.swing.JTextField jTextFieldHire;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLN;
    private javax.swing.JTextField jTextFieldemptype;
    private javax.swing.JCheckBox spanish;
    private javax.swing.JCheckBox turkish;
    // End of variables declaration//GEN-END:variables
}
