/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourisim;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.awt.*;
import java.awt.TrayIcon.MessageType;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import oracle.jdbc.pool.OracleDataSource;
import static tourisim.WithTrip.jTabbedPane1;

/**
 *
 * @author Msys
 */
public class issueticket extends javax.swing.JFrame {
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("TourisimPU");
     EntityManager em=emf.createEntityManager();
    EntityManager eoffer=Persistence.createEntityManagerFactory("TourisimPU").createEntityManager();
    static Integer totalpricereg=0;
    static String passportID="",ticketid="",firstname="",lastname="",travelfrom="",trvaelto="",traveldate="",room="",car="",
            totalprice="",chooseoffer="no",offername="-----",airport="";
   

    /**
     * Creates new form issueticket
     */
    static boolean falg=false,cheack=false;
    private ButtonGroup radio1=new ButtonGroup();
    private ButtonGroup radio2=new ButtonGroup();
     ArrayList<String> arraylist=new ArrayList<String>();
    public issueticket() {
        initComponents();
        super.pack();
        super.setLocationRelativeTo(null);
        radio1.add(jRadioButtonadult);radio1.add(jRadioButtonchild);
       radio2.add(jRadioButtoneconomy); radio2.add(jRadioButtonbuss); radio2.add(jRadioButtonfirst);
       
       //get name of airports from jcombobox and add it to arraylist 
          ComboBoxModel model = jComboBoxAirport.getModel();
         String country=jComboBoxTo.getSelectedItem().toString();
         String []tokens=country.split(" ");
         String s=tokens[tokens.length-1];
                int size = model.getSize();
                for(int i=0;i<size;i++) {
                   
                    Object element = model.getElementAt(i);
                    arraylist.add(element.toString());  
                    
                }//end of for
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jRadioButtonadult = new javax.swing.JRadioButton();
        jRadioButtonchild = new javax.swing.JRadioButton();
        jComboBoxTo = new javax.swing.JComboBox<>();
        jComboBoxFrom = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxAirport = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtoneconomy = new javax.swing.JRadioButton();
        jRadioButtonbuss = new javax.swing.JRadioButton();
        jRadioButtonfirst = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 370));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 170, 183));
        jLabel1.setText("Issuing Ticket");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 170, 183));
        jLabel6.setText("To:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 170, 183));
        jLabel7.setText("From:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 170, 183));
        jLabel8.setText("Airport:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 170, 183));
        jLabel9.setText("Depart:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 170, 183));
        jLabel10.setText("Passenger:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 170, 183));
        jLabel11.setText("Return:");

        jDateChooser1.setBackground(new java.awt.Color(32, 170, 183));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        jDateChooser2.setBackground(new java.awt.Color(32, 170, 183));
        jDateChooser2.setForeground(new java.awt.Color(255, 255, 255));

        jRadioButtonadult.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jRadioButtonadult.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonadult.setText("Adult");

        jRadioButtonchild.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jRadioButtonchild.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonchild.setText("Children");

        jComboBoxTo.setBackground(new java.awt.Color(32, 170, 183));
        jComboBoxTo.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jComboBoxTo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan 1", "Albania 2", "Algeria 3", "Andorra 4", "Angola 5", "Antigua and Barbuda 6", "Argentina 7", "Armenia 8", "Australia 9", "Austria 10", "Azerbaijan 11", "Bahamas 12", "Bahrain 13", "Bangladesh 14", "Barbados 15", "Belarus 16", "Belgium 17", "Belize 18", "Benin 19\t", "Bhutan 20\t", "Bolivia 21\t", "Bosnia and Herzegovina 22", "Botswana 23", "Brazil  24", "Brunei 25", "Bulgaria 26", "Burkina Faso 27", "Burundi 28", "Côte d'Ivoire 29", "Cabo Verde 30", "Cambodia 31", "Cameroon 32", "Canada 33", "Central African Republic 34", "Chad 35", "Chile 36", "China 37", "Colombia 38", "Comoros 39", "Congo (Congo-Brazzaville) 40", "Costa Rica 41", "Croatia 42", "Cuba 43 ", "Cyprus 44", "Czechia (Czech Republic) 45", "Democratic Republic of the Congo 46", "Denmark 47", "Djibouti 48", "Dominica 49", "Dominican Republic 50", "Ecuador 51", "Egypt 52", "El Salvador 53", "Equatorial Guinea 54", "Eritrea 55", "Estonia 56", "Eswatini (fmr. \"Swaziland\") 57", "Ethiopia 58", "Fiji 59", "Finland 60", "France 61", "Gabon 62", "Gambia 63", "Georgia 64", "Germany 65", "Ghana 66", "Greece 67", "Grenada 68", "Guatemala 69", "Guinea 70", "Guinea-Bissau 71", "Guyana 72", "Haiti 73", "Holy See 74", "Honduras 75", "Hungary 76", "Iceland 77", "India 78", "Indonesia 79", "Iran 80", "Iraq 81", "Ireland 82", "Italy 84\t", "Jamaica 85", "Japan 86", "Jordan 87", "Kazakhstan 88", "Kenya 89", "Kiribati 90", "Kuwait 91", "Kyrgyzstan 92", "Laos 93", "Latvia 94", "Lebanon 95", "Lesotho 96", "Liberia 97", "Libya 98", "Liechtenstein 99", "Lithuania 100", "Luxembourg 101", "Madagascar 102", "Malawi 103", "Malaysia 104", "Maldives 105", "Mali 106", "Malta 107", "Marshall Islands 108", "Mauritania 109", "Mauritius 110", "Mexico 111", "Micronesia 112", "Moldova 113", "Monaco 114", "Mongolia 115", "Montenegro 116", "Morocco 117", "Mozambique 118", "Myanmar (formerly Burma) 119", "Namibia 120", "Nauru 121", "Nepal 122", "Netherlands 123", "New Zealand 124", "Nicaragua 125", "Niger 126", "Nigeria 127", "North Korea 128", "North Macedonia 129", "Norway 130", "Oman 131", "Pakistan 132", "Palau 133", "Palestine State 134", "Panama 135 ", "Papua New Guinea 136", "Paraguay 137", "Peru 138", "Philippines 139", "Poland 140", "Portugal 141", "Qatar 142", "Romania 143", "Russia 144", "Rwanda 145", "Saint Kitts and Nevis 146", "Saint Lucia 147", "Saint Vincent and the Grenadines 148", "Samoa 149", "San Marino 150", "Sao Tome and Principe 151", "Saudi Arabia 152", "Senegal 153", "Serbia 154", "Seychelles 155", "Sierra Leone 156", "Singapore 157", "Slovakia 158", "Slovenia 159", "Solomon Islands 160", "Somalia 161", "South Africa 162", "South Korea 163", "South Sudan 164", "Spain 165", "Sri Lanka 166", "Sudan 167", "Suriname 168", "Sweden 169", "Switzerland 170", "Syria 171", "Tajikistan 172", "Tanzania 173", "Thailand 174", "Timor-Leste 175", "Togo 176", "Tonga 177", "Trinidad and Tobago 178", "Tunisia 179", "Turkey 180", "Turkmenistan 181", "Tuvalu 182", "Uganda 183", "Ukraine 184", "United Arab Emirates 185", "United Kingdom 186", "United States of America 187", "Uruguay 188", "Uzbekistan 189", "Vanuatu 190", "Venezuela 191", "Vietnam 192", "Yemen 193", "Zambia 194", "Zimbabwe 195" }));

        jComboBoxFrom.setBackground(new java.awt.Color(32, 170, 183));
        jComboBoxFrom.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jComboBoxFrom.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan 1", "Albania 2", "Algeria 3", "Andorra 4", "Angola 5", "Antigua and Barbuda 6", "Argentina 7", "Armenia 8", "Australia 9", "Austria 10", "Azerbaijan 11", "Bahamas 12", "Bahrain 13", "Bangladesh 14", "Barbados 15", "Belarus 16", "Belgium 17", "Belize 18", "Benin 19\t", "Bhutan 20\t", "Bolivia 21\t", "Bosnia and Herzegovina 22", "Botswana 23", "Brazil  24", "Brunei 25", "Bulgaria 26", "Burkina Faso 27", "Burundi 28", "Côte d'Ivoire 29", "Cabo Verde 30", "Cambodia 31", "Cameroon 32", "Canada 33", "Central African Republic 34", "Chad 35", "Chile 36", "China 37", "Colombia 38", "Comoros 39", "Congo (Congo-Brazzaville) 40", "Costa Rica 41", "Croatia 42", "Cuba 43 ", "Cyprus 44", "Czechia (Czech Republic) 45", "Democratic Republic of the Congo 46", "Denmark 47", "Djibouti 48", "Dominica 49", "Dominican Republic 50", "Ecuador 51", "Egypt 52", "El Salvador 53", "Equatorial Guinea 54", "Eritrea 55", "Estonia 56", "Eswatini (fmr. \"Swaziland\") 57", "Ethiopia 58", "Fiji 59", "Finland 60", "France 61", "Gabon 62", "Gambia 63", "Georgia 64", "Germany 65", "Ghana 66", "Greece 67", "Grenada 68", "Guatemala 69", "Guinea 70", "Guinea-Bissau 71", "Guyana 72", "Haiti 73", "Holy See 74", "Honduras 75", "Hungary 76", "Iceland 77", "India 78", "Indonesia 79", "Iran 80", "Iraq 81", "Ireland 82", "Italy 84\t", "Jamaica 85", "Japan 86", "Jordan 87", "Kazakhstan 88", "Kenya 89", "Kiribati 90", "Kuwait 91", "Kyrgyzstan 92", "Laos 93", "Latvia 94", "Lebanon 95", "Lesotho 96", "Liberia 97", "Libya 98", "Liechtenstein 99", "Lithuania 100", "Luxembourg 101", "Madagascar 102", "Malawi 103", "Malaysia 104", "Maldives 105", "Mali 106", "Malta 107", "Marshall Islands 108", "Mauritania 109", "Mauritius 110", "Mexico 111", "Micronesia 112", "Moldova 113", "Monaco 114", "Mongolia 115", "Montenegro 116", "Morocco 117", "Mozambique 118", "Myanmar (formerly Burma) 119", "Namibia 120", "Nauru 121", "Nepal 122", "Netherlands 123", "New Zealand 124", "Nicaragua 125", "Niger 126", "Nigeria 127", "North Korea 128", "North Macedonia 129", "Norway 130", "Oman 131", "Pakistan 132", "Palau 133", "Palestine State 134", "Panama 135 ", "Papua New Guinea 136", "Paraguay 137", "Peru 138", "Philippines 139", "Poland 140", "Portugal 141", "Qatar 142", "Romania 143", "Russia 144", "Rwanda 145", "Saint Kitts and Nevis 146", "Saint Lucia 147", "Saint Vincent and the Grenadines 148", "Samoa 149", "San Marino 150", "Sao Tome and Principe 151", "Saudi Arabia 152", "Senegal 153", "Serbia 154", "Seychelles 155", "Sierra Leone 156", "Singapore 157", "Slovakia 158", "Slovenia 159", "Solomon Islands 160", "Somalia 161", "South Africa 162", "South Korea 163", "South Sudan 164", "Spain 165", "Sri Lanka 166", "Sudan 167", "Suriname 168", "Sweden 169", "Switzerland 170", "Syria 171", "Tajikistan 172", "Tanzania 173", "Thailand 174", "Timor-Leste 175", "Togo 176", "Tonga 177", "Trinidad and Tobago 178", "Tunisia 179", "Turkey 180", "Turkmenistan 181", "Tuvalu 182", "Uganda 183", "Ukraine 184", "United Arab Emirates 185", "United Kingdom 186", "United States of America 187", "Uruguay 188", "Uzbekistan 189", "Vanuatu 190", "Venezuela 191", "Vietnam 192", "Yemen 193", "Zambia 194", "Zimbabwe 195" }));
        jComboBoxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFromActionPerformed(evt);
            }
        });
        jComboBoxFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFromKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(32, 170, 183));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Done");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(32, 170, 183));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxAirport.setBackground(new java.awt.Color(32, 170, 183));
        jComboBoxAirport.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jComboBoxAirport.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamid Karzai International Airport 1", "Herat International Airport 1", "Kandahar International Airport 1", "Mazar-e Sharif International Airport 1", "Tirana International Airport Nënë Tereza 2", "Batna Airport 3", "Soummam Airport 3", "Zenata Airport 3", "Quatro de Fevereiro Airport 5", "Lubango Airport 5", "VC Bird International Airport 6", "Aeroparque Jorge Newbery 7", "Cataratas del Iguazú International Airport 7", "Resistencia International Airport 7", "Ushuaia International Airport 7", "Zvartnots International Airport 8", "Shirak Airport 8", "Adelaide Airport 9", "Sunshine Coast Airport 9", "Sydney Airport 9", "Graz Airport 10", "Klagenfurt Airport 10", "Innsbruck Airport 10", "Linz Airport 10", "Salzburg Airport 10", "Vienna International Airport 10", "Heydar Aliyev International Airport 11", "Ganja International Airport 11", "Nakhchivan Airport 11", "Qabala International Airport 11", "Lankaran International Airport 11", "Zaqatala International Airport 11", "Lynden Pindling International Airport 12", "Chub Cay International Airport 12", "Exuma International Airport 12", "Grand Bahama International Airport 12", "Rock Sound International Airport 12", "Marsh Harbour International Airport 12", "Bahrain International Airport 13", "Shah Amanat International Airport 14", "Hazrat Shahjalal International Airport 14", "Osmani International Airport 14", "Grantley Adams International Airport 15", "Hrodna Airport 16", "Gomel Airport 16", "Minsk International Airport 16", "Antwerp International Airport 17", "Brussels Airport 17", "Brussels South Charleroi Airport 17", "Liège Airport 17", "Ostend-Bruges International Airport 17", "Philip S. W. Goldson International Airport 18", "Cadjehoun Airport 19", "Paro Airport 20", "El Alto International Airport 21", "Viru Viru International Airport 21", "Jorge Wilstermann International Airport 21", "Sarajevo International Airport 22", "Tuzla International Airport 22", "Mostar International Airport 22", "Maun Airport 23", "Francistown Airport 23", "Kasane Airport 23", "Santa Maria Airport 24", "Tancredo Neves International Airport 24", "Brasília International Airport 24", "Brunei International Airport 25", "Burgas Airport 26", "Plovdiv Airport 26", "Sofia Airport 26", "Bobo Dioulasso Airport 27", "Ouagadougou Airport 27", "Bujumbura International Airport 28", "Port Bouet Airport 29", "Phnom Penh International Airport 31", "Siem Reap International Airport 31", "Sihanouk International Airport 31", "Douala Airport 32", "Nsimalen Airport 32", "Calgary International Airport 33", "Edmonton International Airport 33", "Ottawa Macdonald-Cartier International Airport 33", "M'Poko International Airport 34", "N'Djamena International Airport 35", "Cerro Moreno International Airport 36", "Carriel Sur International Airport 36", "El Tepual International Airport 36", "Yanji Airport 37", "Yuncheng Guangong Airport 37", "Meixian Airport 37", "El Edén International Airport 38", "Jorge Isaacs Airport 38", "Los Garzones International Airport 38", "Prince Said Ibrahim International Airport 39", "Pointe Noire Airport 40", "Maya-Maya Airport 40", "Daniel Oduber Quirós International Airport 41", "Juan Santamaría International Airport 41", "Brač Airport 42", "Dubrovnik Airport 42", "Zadar Airport 42", "Ignacio Agramonte International Airport 43", "Jaime González Airport 43", "Frank País Airport 43", "Larnaca International Airport 44", "Paphos International Airport 44", "Ercan International Airport 44", "Brno-Tuřany Airport 45", "Karlovy Vary Airport 45", "Prague Václav Havel Airport 45", "Goma International Airport 46", "Bangoka International Airport 46", "Lubumbashi International Airport 46", "Aalborg Airport 47", "Aarhus Airport 47", "Copenhagen Airport 47", "Djibouti–Ambouli International Airport 48", "Melville Hall Airport 49", "María Montez International Airport 50", "La Romana International Airport 50", "Punta Cana International Airport 50", "Mariscal Lamar International Airport 51", "Carlos Concha Torres International Airport 51", "José Joaquín de Olmedo International Airport 51", "Borg El Arab Airport 52", "Cairo International Airport 52", "Aswan International Airport 52", "Monseñor Óscar Arnulfo Romero International Airport 53", "Malabo International Airport 54", "Asmara International Airport 55", "Lennart Meri Tallinn Airport 56", "Tartu Airport 56", "King Mswati III International Airport 57", "Addis Ababa Bole International Airport 58", "Aba Tenna Dejazmach Yilma International Airport 58", "Nadi International Airport 59", "Nausori International Airport 59", "Mariehamn Airport 60", "Kuusamo Airport 60", "Turku Airport 60", "Campo dell'Oro Airport 61", "Orly Airport 61", "Saint-Exupéry Airport 61", "M'Vengue El Hadj Omar Bongo Ondimba International Airport 62", "Libreville International Airport 62", "Port-Gentil International Airport 62", "Banjul International Airport 63", "Ambrolauri Airport 64", "Queen Tamar Airport 64", "Tbilisi International Airport 64", "Berlin Brandenburg Airport 65", "Langenhagen Airport 65", "Frankfurt Airport 65", "Kotoka International Airport 66", "Tamale Airport 66", "Athens International Airport 67", "Chania International Airport 67", "Chios Island National Airport 67", "Maurice Bishop International Airport 68", "Mundo Maya International Airport 69", "La Aurora International Airport 69", "Jacksons International Airport 70", "Mount Hagen Airport 70", "Osvaldo Vieira International Airport 71", "Bubaque Airport 71", "Cheddi Jagan International Airport 72", "Cap-Haïtien International Airport 73", "Toussaint Louverture International Airport 73", "Golosón International Airport 75", "Juan Manuel Gálvez International Airport 75", "Ramón Villeda Morales International Airport 75", "Budapest Ferenc Liszt International Airport 76", "Debrecen International Airport 76", "Hévíz-Balaton Airport 76", "Akureyri Airport 77", "Keflavik International Airport 77", "Reykjavik Airport 77", "Kempegowda International Airport 78", "Indira Gandhi International Airport 78", "Tiruchirappalli International Airport 78", "Sultan Aji Muhammad Sulaiman Airport 79", "Sultan Iskandar Muda International Airport 79", "Radin Inten II International Airport 79", "Abadan International Airport 80", "Ahvaz International Airport 80", "Arak International Airport 80", "Al Najaf International Airport 81", "Baghdad International Airport 81", "Basra International Airport 81", "Cork Airport 82", "Dublin Airport 82", "Ireland West Airport Knock 82", "Fertilia Airport 84", "Linate Airport 84", "Rome Ciampino Airport 84", "Norman Manley International Airport 85", "Sangster International Airport 85", "Akita Airport 86", "Oita Airport 86", "Haneda International Airport 86", "King Hussein International Airport 87", "Queen Alia International Airport 87", "Aktau Airport 88", "Aktobe International Airport 88", "Almaty International Airport 88", "Eldoret International Airport 89", "Moi International Airport 89", "Kisumu International Airport 89", "Cassidy International Airport 90", "Bonriki International Airport 90", "Kuwait International Airport 91", "Manas Airport 92", "Issyk-Kul International Airport 92", "Karakol International Airport 92", "Luang Prabang International Airport 93", "Pakse International Airport 93", "Savannakhet Airport 93", "Riga International Airport 94", "Ventspils International Airport 94", "Beirut Rafic Hariri International Airport 95", "Moshoeshoe I International Airport 96", "Roberts International Airport 97", "Benina International Airport 98", "Sebha Airport 98", "Tripoli International Airport 98", "Friedrichshafen Airport 99", "Kaunas Airport 100", "Palanga International Airport 100", "Findel Airport\t101", "Ivato International Airport 102", "Arrachart Airport 102", "Chileka International Airport 103", "Lilongwe International Airport 103", "Sultan Abdul Halim Airport 104", "Sultan Azlan Shah Airport 104", "Kota Kinabalu International Airport 104", "Velana International Airport 105", "Gan International Airport 105", "Senou International Airport 106", "Malta International Airport 107", "Bucholz Army Airfield 108", "Marshall Islands International Airport 108", "Nouakchott–Oumtounsy International Airport 109", "Nouadhibou International Airport 109", "Sir Seewoosagur Ramgoolam International Airport 110", "General Juan N. Alvarez International Airport 111", "Lic. Jesús Terán Peredo International Airport 111", "Cancun International Airport 111", "Chuuk International Airport 112", "Kosrae International Airport 112", "Pohnpei International Airport 112", "Chişinău International Airport 113", "Chinggis Khaan International Airport 115", "Podgorica Airport 116", "Tivat Airport 116", "Al Massira Airport 117", "Mohammed V International Airport 117", "Maputo International Airport 118", "Beira Airport 118", "Inhambane Airport 118", "Bagan Airport 119", "Hosea Kutako International Airport 120", "Walvis Bay Airport 120", "Nauru International Airport 121", "Tribhuvan International Airport 122", "Flamingo International Airport 123", "Juancho E. Yrausquin Airport 123", "Auckland Airport 124", "Christchurch International Airport 124", "Queenstown Airport 124", "Augusto C. Sandino International Airport 125", "Bluefields Airport 125", "Diori Hamani International Airport 126", "Nnamdi Azikiwe International Airport 127", "Pyongyang International Airport 128", "Ohrid St. Paul the Apostle Airport 129", "Skopje International Airport 129", "Ålesund Airport 130", "Bergen Airport 130", "Muscat International Airport 131", "Salalah International Airport 131", "Sohar International Airport 131", "Bahawalpur Airport 132", "Roman Tmetuchl International Airport 133", "Ramon Airport 134", "Haifa Airport 134", "Ben Gurion Airport 134", "Bocas del Toro \"Isla Colón\" International Airport 135", "Enrique Malek International Airport 135", "Jacksons International Airport 136", "Mount Hagen Airport 136", "Silvio Pettirossi International Airport 137", "Rodríguez Ballón International Airport 138", "Basco Airport 139", "Cagayan North International Airport 139", "Bydgoszcz Ignacy Jan Paderewski Airport 140", "Katowice International Airport 140", "Beja Airport 141", "Porto Santo Airport 141", "Hamad International Airport 142", "Arad International Airport 143", "George Enescu International Airport 143", "Abakan International Airport 144", "Ugolny Airport 144", "Anapa Airport 144", "Kigali International Airport 145", "Robert L. Bradshaw International Airport 146", "Hewanorra International Airport 147", "Argyle International Airport 148", "Canouan Airport 148", "Pago Pago International Airport 149", "São Tomé International Airport 151", "Abha International Airport 152", "Al-Ahsa International Airport 152", "Al-Jawf Airport 152", "Blaise Diagne International Airport 153", "Belgrade Nikola Tesla Airport 154", "Niš Constantine the Great Airport 154", "Morava Airport 154", "Seychelles International Airport 155", "Lungi International Airport 156", "Singapore Changi Airport 157", "Seletar Airport 157", "M. R. Štefánik Airport 158", "Košice International Airport 158", "Piešťany Airport 158", "Ljubljana Jože Pučnik Airport 159", "Portorož Airport 159", "Honiara International Airport 160", "Bosaso Airport 161", "Abdullahi Yusuf Airport 161", "Garowe Airport 161", "Cape Town International Airport 162", "King Shaka International Airport 162", "Gimhae International Airport 163", "Juba International Airport 164", "Alvedro Airport 165", "Almería International Airport 165", "Bandaranaike International Airport 166", "Mattala Rajapaksa International Airport 166", "Ratmalana International Airport 166", "Khartoum International Airport 167", "Port Sudan New International Airport 167", "Johan Adolf Pengel International Airport 168", "Göteborg Landvetter Airport 169", "Bern-Belp Airport 170", "Geneva International Airport 170", "Aleppo International Airport 171", "Damascus International Airport 171", "Bassel Al-Assad International Airport 171", "Qamishli Airport 171", "Bokhtar International Airport 172", "Dushanbe Airport 172", "Arusha Airport 173", "Suvarnabhumi Airport 174", "Tokoin Airport 176", "Fuaʻamotu International Airport\t 177", "Vava'u International Airport 177", "Piarco International Airport 178", "Arthur Napoleon Raymond Robinson International Airport 178", "Zarzis Airport 179", "Şakirpaşa Airport 180", "Gazipaşa Airport 180", "Esenboğa International Airport 180", "Antalya Airport 180", "Ashgabat Airport 181", "Turkmenbashi International Airport 181", "Funafuti International Airport 182", "Arua Airport 183", "Entebbe International Airport 183", "Gulu Airport 183", "Boryspil International Airport 184", "Chernivtsi International Airport 184", "Abu Dhabi International Airport 185", "Al Ain International Airport 185", "Dubai International Airport 185", "Birmingham International Airport 186", "Bristol Airport 186", "Carrasco International Airport 188", "Capitan Corbeta CA Curbelo International Airport 188", "Andizhan Airport 189", "Bukhara International Airport 189", "Santo-Pekoa International Airport 190", "Bauerfield International Airport 190", "Simón Bolívar International Airport 191", "La Chinita International Airport 191", "Arturo Michelena International Airport 191", "Da Nang International Airport 192", "Noi Bai International Airport 192", "Aden International Airport 193", "Sana'a International Airport 193", "Seiyun Airport 193", "Harry Mwanga Nkumbula International Airport 194", "Kenneth Kaunda International Airport 194\t", "Simon Mwansa Kapwepwe International Airport 194", "Robert Gabriel Mugabe International Airport 195", "Victoria Falls Airport 195", "Joshua Mqabuko Nkomo International Airport 195" }));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 170, 183));
        jLabel12.setText("Class:");

        jRadioButtoneconomy.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jRadioButtoneconomy.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtoneconomy.setText("Economy");

        jRadioButtonbuss.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jRadioButtonbuss.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonbuss.setText("Bussiness");

        jRadioButtonfirst.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jRadioButtonfirst.setForeground(new java.awt.Color(32, 170, 183));
        jRadioButtonfirst.setLabel("First");
        jRadioButtonfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonadult, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonchild, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtoneconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonbuss, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonfirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTo, 0, 269, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jRadioButtonadult)
                            .addComponent(jRadioButtonchild)
                            .addComponent(jLabel12)
                            .addComponent(jRadioButtoneconomy)
                            .addComponent(jRadioButtonbuss)
                            .addComponent(jRadioButtonfirst)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jComboBoxFrom.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxFromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFromKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {ComboBoxModel model = jComboBoxAirport.getModel();
         String country=jComboBoxFrom.getSelectedItem().toString();
         String []tokens=country.split(" ");
         String s=tokens[tokens.length-1];
                int size = model.getSize();
                jComboBoxAirport.removeAllItems();
                   for(String oneAir:arraylist)
                   {
                       String []airportlist=oneAir.split(" ");
                       if(s.equalsIgnoreCase(airportlist[airportlist.length-1] ))
                    {
                        jComboBoxAirport.addItem(oneAir);
                
                    }   
                   }//end of for
        }
    }//GEN-LAST:event_jComboBoxFromKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{    
        RegisterClients register=new RegisterClients();
       IssueTicket_1 issue=new IssueTicket_1();
       Clients client=new Clients();
       ClassTicket ct=new ClassTicket();
       Passenger passenger=new Passenger();
       Person person=new Person();
       //get first name and last name:
       Query qryperson=eoffer.createNamedQuery("Person.findAll");
       Query qryclient=eoffer.createNamedQuery("Clients.findAllorder");
        java.util.List<Clients> clientlist=qryclient.getResultList();
        java.util.List<Person> personlist=qryperson.getResultList();
       for(Clients c:clientlist)
       {
           if(c.getPassportId().compareTo(BigDecimal.valueOf(Long.parseLong(question.passid)))==0)
           {
               person=c.getPersonalId();
               for(Person p:personlist)
               {
                   if(p.getPersonalId().compareTo(person.getPersonalId())==0)
                   {
                       firstname=p.getFirstName(); lastname=p.getLastName();
                   }
               }
           }
       }
       
       
                   //add to register:
        Query qry=eoffer.createNamedQuery("IssueTicket_1.findAllorder");
       Query qryreg=eoffer.createNamedQuery("RegisterClients.findAllorder");
       //Query qryperson=eoffer.createNamedQuery("RegisterClients.findAllorder");
        
        java.util.List<IssueTicket_1> issuelist=qry.getResultList();
        BigDecimal ticketID = null;
        BigInteger price=null; 
        passportID=question.passid; 
       
        
        for(IssueTicket_1 ticket:issuelist)
        {
            ticketID=ticket.getTicketId();
        }
        Integer ticketid;
        if(ticketID==null)
        {
            ticketid=100;
            
        }
        else
        {
            ticketid=ticketID.intValue()+1;
        }  
        issueticket.ticketid=ticketid.toString(); 
        BigDecimal bigtickID=BigDecimal.valueOf(ticketid);
        issue.setTicketId(bigtickID);
        BigDecimal bdpassport=BigDecimal.valueOf(Long.parseLong(question.passid));
       client.setPassportId(bdpassport);
        issue.setPassportId(client);
        issue.setAirportname(jComboBoxAirport.getSelectedItem().toString());
        issue.setTravelfrom(jComboBoxFrom.getSelectedItem().toString());
        issue.setTravelto(jComboBoxTo.getSelectedItem().toString());
        issue.setTravelDate(jDateChooser2.getDate());
        issue.setReturnDate(jDateChooser1.getDate());
         travelfrom=issue.getTravelfrom(); trvaelto=issue.getTravelto();
        traveldate=issue.getTravelDate().toString();
        airport=issue.getAirportname();
        if(jRadioButtoneconomy.isSelected())
        {
            ct.setClassType("Economy");
            ct.setClassPrice(BigInteger.valueOf(Long.parseLong("30")));
            issue.setClassType(ct);            
            price=ct.getClassPrice();
            price=BigInteger.valueOf(price.intValue()+ct.getClassPrice().intValue());
        }
        else if(jRadioButtonbuss.isSelected())
        {
            ct.setClassType("Bussiness");
            ct.setClassPrice(BigInteger.valueOf(Long.parseLong("50")));
            issue.setClassType(ct);
            price=ct.getClassPrice();
            price=BigInteger.valueOf(price.intValue()+ct.getClassPrice().intValue());

            
        }
        else if(jRadioButtonfirst.isSelected())
        {
            ct.setClassType("First");
            ct.setClassPrice(BigInteger.valueOf(Long.parseLong("75")));
            issue.setClassType(ct);
            price=ct.getClassPrice();
            price=BigInteger.valueOf(price.intValue()+ct.getClassPrice().intValue());
        }
        if(jRadioButtonadult.isSelected())
        {
        passenger.setPassengerType("Adult");
        passenger.setPassengerPrice(BigInteger.valueOf(Long.parseLong("10")));
            issue.setPassengerType(passenger); 
            price=passenger.getPassengerPrice();
            price=BigInteger.valueOf(price.intValue()+ct.getClassPrice().intValue());
        }
        else if(jRadioButtonchild.isSelected())
        {
            passenger.setPassengerType("Children");
              passenger.setPassengerPrice(BigInteger.valueOf(Long.parseLong("5")));
            issue.setPassengerType(passenger);  
            price=passenger.getPassengerPrice();
            price=BigInteger.valueOf(price.intValue()+ct.getClassPrice().intValue());
        }
        issue.setTotalPrice(price);
      int response=JOptionPane.showConfirmDialog(this,"Do You Want Book Room?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION)
        {
            this.dispose();
            alonetravel.h.setVisible(true);
            totalpricereg=issue.getTotalPrice().intValue();
            cheack=true;
        }
        else if(response==JOptionPane.NO_OPTION)
        {
        int response1=JOptionPane.showConfirmDialog(this,"Do You Want To Take Car?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);   
        if(response1==JOptionPane.YES_OPTION)
        {
          this.dispose();
          alonetravel.tc.setVisible(true);
           totalpricereg=issue.getTotalPrice().intValue();
        }
        else if(response1==JOptionPane.NO_OPTION)
        {
            java.util.List<RegisterClients> reglist=qryreg.getResultList();
            BigDecimal regID = null;
        for(RegisterClients rc:reglist)
        {
           regID=rc.getRegisteerId();
        }
        Integer registerID;
        if(regID==null)
        {
            registerID=20;
        }
        else
        {
            registerID=regID.intValue()+1;
        }
        BigDecimal bigregisterID=BigDecimal.valueOf(registerID);
        register.setRegisteerId(bigregisterID);
        register.setRegisteerId(register.getRegisteerId());
        //BigDecimal bdpassport1=BigDecimal.valueOf(Long.parseLong(question.passid));
        client.setPassportId(bdpassport);
        register.setPassportId(client);
        ClientType ctype=new ClientType();
        ctype.setClientsType("nt");
        register.setClientsType(ctype);
        register.setTotalPrice(price);
        totalprice=register.getTotalPrice().toString();
        
        radio1.clearSelection();
        radio2.clearSelection();
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        JOptionPane.showMessageDialog(this, "Successfully Issueing Ticket", "Information", JOptionPane.INFORMATION_MESSAGE);
        
         
         //email:
         sendMail("air333761@gmail.com");
        
        
             if(falg)
             {
            try {
                Thread.sleep(7000);
            } catch (InterruptedException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
                  if (SystemTray.isSupported()) {
            issueticket td = new issueticket();
            try {
                td.displayTray();
            } catch (AWTException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.err.println("System tray not supported!");
        }
             }
             
             //bill:
              room="no"; car="no"; chooseoffer="no"; offername="-----";
             new try_report().setVisible(true);
            
         em.persist(register);
        }//end else if
        }
        
       
        em.getTransaction().begin();
        em.persist(issue);
       
        em.getTransaction().commit();
        em.close();
        //eoffer.close();
        
        }
        catch(Exception e)
        {
           Logger.getLogger(WithTrip.class.getName()).log(Level.SEVERE, null, e); 
        }

      







       /* sendMail("air333761@gmail.com");
        
        
             if(falg)
             {
            try {
                Thread.sleep(7000);
            } catch (InterruptedException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
                  if (SystemTray.isSupported()) {
            issueticket td = new issueticket();
            try {
                td.displayTray();
            } catch (AWTException ex) {
                Logger.getLogger(issueticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.err.println("System tray not supported!");
        }
             }*/
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFromActionPerformed

    private void jRadioButtonfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfirstActionPerformed

     public static void  sendMail(String recepient)
    {
        System.out.println("prepare");
        Properties properties=new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        String myAccountEmail="air333761@gmail.com";
        String password="123456air?";
        Session session=Session.getInstance(properties,new Authenticator(){
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(myAccountEmail,password);
            }
            
        });
        Message message=prepareMessage(session,myAccountEmail,recepient);
        try {
            Transport.send(message);
        } catch (Exception ex) {
            //Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error1");
        }
        
        System.out.println("message sent successfully");
        falg=true;
        
      
        
    }
    //function to write message
    private static Message prepareMessage(Session session,String myAccountEmail,String recepient){
      
        try {
            Message message=new MimeMessage(session);
            message.setFrom(new InternetAddress(myAccountEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient));
            message.setSubject("CONFIRM BOOKING");
            message.setText("This message is sent to "+airport+" to confirm the booking inquired by "+firstname+" "+lastname+
                    " his/her passport ID is "+question.passid+"\nRegards.");
            return message;
        } catch (Exception ex) {
            //Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error2");
        }
      return null;
    }//end of funtion
    
    //Notification:
        public void displayTray() throws AWTException {
        //Obtain only one instance of the SystemTray object
        SystemTray tray = SystemTray.getSystemTray();

        //If the icon is a file
        Image image = Toolkit.getDefaultToolkit().createImage("icon.png");
        //Alternative (if the icon is on the classpath):
        //Image image = Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"));

        TrayIcon trayIcon = new TrayIcon(image, "Tray Demo");
        //Let the system resize the image if needed
        trayIcon.setImageAutoSize(true);
        //Set tooltip text for the tray icon
        trayIcon.setToolTip("System tray icon demo");
        tray.add(trayIcon);
        //trayIcon.displayMessage("Hello, World", "notification demo", MessageType.INFO);
//trayIcon.displayMessage("Hallo /nWOrld"
//                , "Cofirmation", TrayIcon.MessageType.INFO);
        trayIcon.displayMessage("Booking for "+firstname+" "+lastname+" His/Her Passport ID is: "+question.passid+" Confirmed."
                , "Cofirmation", TrayIcon.MessageType.INFO);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issueticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issueticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issueticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issueticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxAirport;
    private javax.swing.JComboBox<String> jComboBoxFrom;
    private javax.swing.JComboBox<String> jComboBoxTo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonadult;
    private javax.swing.JRadioButton jRadioButtonbuss;
    private javax.swing.JRadioButton jRadioButtonchild;
    private javax.swing.JRadioButton jRadioButtoneconomy;
    private javax.swing.JRadioButton jRadioButtonfirst;
    // End of variables declaration//GEN-END:variables
}
