/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourisim;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import static tourisim.New_Offer.jTabbedPane1;
import static tourisim.issueticket.firstname;
import static tourisim.issueticket.lastname;

/**
 *
 * @author Msys
 * 
 */
public class WithTrip extends javax.swing.JFrame {
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("TourisimPU");
     EntityManager em=emf.createEntityManager();
    EntityManager eoffer=Persistence.createEntityManagerFactory("TourisimPU").createEntityManager();
    

    /**
     * Creates new form WithTrip
     */
     private JLabel labelimage=new JLabel();
  
    public WithTrip() {
        initComponents();
        super.pack();
        super.setLocationRelativeTo(null);
        JPanel jPaneltab = new javax.swing.JPanel(new GridLayout(1,2));
         Color c=new Color(32,170,183);
       jPaneltab.setBackground(c);
        JTextArea area=new JTextArea(50,50);
       area.setBackground(Color.white);
       area.setForeground(c);
       jPaneltab.add(area);
       //jTabbedPane1.setBackgroundAt(0, Color.RED);
       //jTabbedPane1.setBackground(Color.WHITE);
       jTabbedPane1.setForeground(c);
       labelimage.setBounds(new Rectangle(new Point(10, 10), labelimage.getPreferredSize()));
      jPaneltab.add(labelimage);

      //jTabbedPane1.addTab("TRY", jPaneltab);
      
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPaneloffers1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(32, 170, 183));
        jPanel8.setPreferredSize(new java.awt.Dimension(872, 300));

        jPaneloffers1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(32, 170, 183));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chooseoffer.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back without trip.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneloffers1Layout = new javax.swing.GroupLayout(jPaneloffers1);
        jPaneloffers1.setLayout(jPaneloffers1Layout);
        jPaneloffers1Layout.setHorizontalGroup(
            jPaneloffers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneloffers1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneloffers1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPaneloffers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
        );
        jPaneloffers1Layout.setVerticalGroup(
            jPaneloffers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneloffers1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPaneloffers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPaneloffers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        two_options to=new two_options();
       question q=new question();
       q.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        try{
             Clients client=new Clients();
                 Offers_1 of=new Offers_1();
        RegisterClients register=new RegisterClients();
        Person person=new Person();
          BigInteger price=null; 
          
          //get first name and last name:
       Query qryperson=eoffer.createNamedQuery("Person.findAll");
       Query qryclient=eoffer.createNamedQuery("Clients.findAllorder");
        java.util.List<Clients> clientlist=qryclient.getResultList();
        java.util.List<Person> personlist=qryperson.getResultList();
       for(Clients c:clientlist)
       {
           if(c.getPassportId().compareTo(BigDecimal.valueOf(Long.parseLong(question.passid)))==0)
           {
               person=c.getPersonalId();
               for(Person p:personlist)
               {
                   if(p.getPersonalId().compareTo(person.getPersonalId())==0)
                   {
                       firstname=p.getFirstName(); lastname=p.getLastName();
                   }
               }
           }
       }
                   //add to register:
        Query qry=eoffer.createNamedQuery("Offers_1.findAll");
        Query qryreg=eoffer.createNamedQuery("RegisterClients.findAllorder");
        
        List<Offers_1> offerlist=qry.getResultList();
        List<RegisterClients> reglist=qryreg.getResultList();
        String offername=jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex());
        
        for(Offers_1 offer:offerlist)
        {
        if(offer.getOfferName().equals(offername))
        {
         price =offer.getPrice();
         issueticket.trvaelto=offer.getDescriptions();
         issueticket.traveldate=offer.getOfferStartDate().toString();
          break;
        }//end if
        }  //end for
          
        BigDecimal regID = null;
        for(RegisterClients rc:reglist)
        {
           regID=rc.getRegisteerId();
        }
        Integer registerID;
        if(regID==null)
        {
            registerID=20;
        }
        else
        {
            registerID=regID.intValue()+1;
        }
      
        BigDecimal bigregisterID=BigDecimal.valueOf(registerID);
        register.setRegisteerId(bigregisterID);
        register.setRegisteerId(register.getRegisteerId());
        BigDecimal bdpassport=BigDecimal.valueOf(Long.parseLong(question.passid));
        
        client.setPassportId(bdpassport);
        register.setPassportId(client);
        ClientType ct=new ClientType();
        ct.setClientsType("wt");
        register.setClientsType(ct);
        register.setTotalPrice(price);
        issueticket.totalprice=register.getTotalPrice().toString();
        
        
        em.getTransaction().begin();
        em.persist(register);
        em.getTransaction().commit();
        em.close();
        //eoffer.close();
        
        }
        catch(Exception e)
        {
           Logger.getLogger(WithTrip.class.getName()).log(Level.SEVERE, null, e); 
        }
      
        try {
                  
               DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
               String url,user,password;
               url="jdbc:oracle:thin:@localhost:1521:xe";
               user="c##Travel";
               password="987654";
               Connection con=DriverManager.getConnection(url,user,password);
               Statement stmt=con.createStatement();
               con.setAutoCommit(false);
               String sqlstr = null;
              
               int pass=Integer.parseInt(question.passid);
               
               //BigDecimal pass=BigDecimal.valueOf(Long.parseLong(question.passid));
               //client.setPassportId(pass);
               String offername=jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex());
               issueticket.offername=offername;
               
               sqlstr="insert into CHOOSE_OFFER values("+pass+",'"+offername+"')";
                   stmt.executeUpdate(sqlstr);
                   con.commit();
               con.close();
               JOptionPane.showMessageDialog(this, "Offer Added Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
               
               //bill:
               issueticket.passportID=question.passid;  issueticket.ticketid="-----"; 
               issueticket.room="no"; issueticket.car="no"; issueticket.chooseoffer="yes";
               issueticket.travelfrom="Palestine";
               new try_report().setVisible(true);
               
//               this.dispose(); 
//               question q=new question();
//               q.setVisible(true);
                         
            }
            catch (Exception ex) {
               Logger.getLogger(WithTrip.class.getName()).log(Level.SEVERE, null, ex);
           }
        


//  JOptionPane.showMessageDialog(this, "Deleted Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithTrip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JPanel jPaneloffers1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
